<?php
/**
 * Curated photo library - the picks from Erika's photo collection, sorted by placement.
 *
 * Each library is one kind of slot (hero headshot, stage, sold sign...). Photos are
 * ranked A1, A2, A3... where A1 is the recommended shot; the admin shows the whole
 * set so a slot can be swapped to an alternate without re-uploading anything.
 *
 * 'pos' is the photo's focal point as "X Y" percentages - where the subject's face
 * sits. Slots crop with object-fit:cover, so without this a portrait photo dropped
 * into a landscape slot gets cropped through the middle and loses the head. Anything
 * the client repositions by hand in the admin overrides it.
 *
 * 'slots' maps a field key from fields.php to its library and the rank used as that
 * slot's default. Fields not listed here keep the plain upload-only picture box.
 */
return [
    'libraries' => [
        '01' => [
            'title' => 'Hero headshots',
            'photos' => [
                ['r' => 'A1', 'f' => 'assets/photos/01/a1-red-blazer-black.jpg', 'label' => 'Red blazer, black backdrop', 'note' => '', 'pos' => '53 33'],
                ['r' => 'A2', 'f' => 'assets/photos/01/a2-red-blazer-blue.jpg', 'label' => 'Red blazer, blue backdrop', 'note' => '', 'pos' => '55 49'],
                ['r' => 'A3', 'f' => 'assets/photos/01/a3-black-and-white-gold.jpg', 'label' => 'Black & white on gold', 'note' => '', 'pos' => '53 42'],
                ['r' => 'A4', 'f' => 'assets/photos/01/a4-soft-portrait.jpg', 'label' => 'Soft portrait, middle part', 'note' => '', 'pos' => '48 45'],
                ['r' => 'A5', 'f' => 'assets/photos/01/a5-patent-jacket.jpg', 'label' => 'Patent jacket, close crop', 'note' => '', 'pos' => '50 41'],
                ['r' => 'A6', 'f' => 'assets/photos/01/a6-office-headshot-ai.jpg', 'label' => 'Headshot in an office setting', 'note' => 'AI-generated', 'pos' => '53 34'],
                ['r' => 'A7', 'f' => 'assets/photos/01/a7-pink-suit-ai.jpg', 'label' => 'Pink suit, three-quarter', 'note' => 'AI-generated', 'pos' => '45 19'],
            ],
        ],
        '02' => [
            'title' => 'Full-body & cut-outs',
            'photos' => [
                ['r' => 'A1', 'f' => 'assets/photos/02/a1-jumpsuit-standing.jpg', 'label' => 'Black jumpsuit, standing', 'note' => 'white background', 'pos' => ''],
                ['r' => 'A2', 'f' => 'assets/photos/02/a2-laughing-hands-hips.jpg', 'label' => 'Laughing, hands on hips', 'note' => 'white background', 'pos' => ''],
                ['r' => 'A3', 'f' => 'assets/photos/02/a3-pointing-thumbs-up.jpg', 'label' => 'Pointing, thumbs up', 'note' => 'white background', 'pos' => ''],
                ['r' => 'A4', 'f' => 'assets/photos/02/a4-suit-pointing-left.webp', 'label' => 'Black suit, pointing left', 'note' => 'transparent', 'pos' => ''],
                ['r' => 'A5', 'f' => 'assets/photos/02/a5-suit-pointing-up.webp', 'label' => 'Black suit, pointing up', 'note' => 'transparent', 'pos' => ''],
                ['r' => 'A6', 'f' => 'assets/photos/02/a6-jumpsuit-cutout.webp', 'label' => 'Black jumpsuit, cut out', 'note' => 'transparent', 'pos' => ''],
            ],
        ],
        '03' => [
            'title' => 'Keynote & stage',
            'photos' => [
                ['r' => 'A1', 'f' => 'assets/photos/03/a1-mic-mid-gesture.jpg', 'label' => 'Mic in hand, mid-gesture', 'note' => '', 'pos' => '49 15'],
                ['r' => 'A2', 'f' => 'assets/photos/03/a2-stage-wide.jpg', 'label' => 'Full stage, wide', 'note' => '', 'pos' => '51 18'],
                ['r' => 'A3', 'f' => 'assets/photos/03/a3-speaking-to-room.jpg', 'label' => 'Speaking to the room', 'note' => '', 'pos' => '50 15'],
                ['r' => 'A4', 'f' => 'assets/photos/03/a4-main-stage-conference.jpg', 'label' => 'Main stage, Mega Systems conference', 'note' => '', 'pos' => '38 15'],
                ['r' => 'A5', 'f' => 'assets/photos/03/a5-stage-led-backdrop.jpg', 'label' => 'Stage with branded LED wall', 'note' => '', 'pos' => '31 18'],
                ['r' => 'A6', 'f' => 'assets/photos/03/a6-at-the-podium.jpg', 'label' => 'At the podium', 'note' => '', 'pos' => '42 26'],
                ['r' => 'A7', 'f' => 'assets/photos/03/a7-keynote-audience-ai.jpg', 'label' => 'Keynote, audience and screens', 'note' => 'AI-generated', 'pos' => '50 45'],
                ['r' => 'A8', 'f' => 'assets/photos/03/a8-keynote-packed-room-ai.jpg', 'label' => 'Keynote to a packed room', 'note' => 'AI-generated', 'pos' => '59 47'],
                ['r' => 'A9', 'f' => 'assets/photos/03/a9-keynote-wide-stage-ai.jpg', 'label' => 'Keynote, wide stage', 'note' => 'AI-generated', 'pos' => '52 54'],
            ],
        ],
        '04' => [
            'title' => 'Panels & industry events',
            'photos' => [
                ['r' => 'A1', 'f' => 'assets/photos/04/a1-panel-four-panelists.jpg', 'label' => 'Four panelists on stage', 'note' => '', 'pos' => '55 45'],
                ['r' => 'A2', 'f' => 'assets/photos/04/a2-panel-wide-room.jpg', 'label' => 'Panel, wide room', 'note' => '', 'pos' => '47 40'],
                ['r' => 'A3', 'f' => 'assets/photos/04/a3-levelup-at-the-table.jpg', 'label' => 'LevelUp Tour, at the table', 'note' => '', 'pos' => '48 29'],
                ['r' => 'A4', 'f' => 'assets/photos/04/a4-conference-group.jpg', 'label' => 'Conference group photo', 'note' => '', 'pos' => '51 39'],
            ],
        ],
        '05' => [
            'title' => 'Coaching & mentorship',
            'photos' => [
                ['r' => 'A1', 'f' => 'assets/photos/05/a1-teaching-with-mic.jpg', 'label' => 'Teaching a room, microphone', 'note' => '', 'pos' => '36 45'],
                ['r' => 'A2', 'f' => 'assets/photos/05/a2-training-room-agents.jpg', 'label' => 'Training room, agents at work', 'note' => '', 'pos' => '49 37'],
                ['r' => 'A3', 'f' => 'assets/photos/05/a3-hands-on-coaching.jpg', 'label' => 'Hands-on coaching', 'note' => '', 'pos' => '25 56'],
                ['r' => 'A4', 'f' => 'assets/photos/05/a4-class-in-session.jpg', 'label' => 'Class in session', 'note' => '', 'pos' => '29 53'],
                ['r' => 'A5', 'f' => 'assets/photos/05/a5-mastermind-candid.jpg', 'label' => 'Mastermind classroom, candid', 'note' => '', 'pos' => '25 61'],
            ],
        ],
        '06' => [
            'title' => 'Desk & office',
            'photos' => [
                ['r' => 'A1', 'f' => 'assets/photos/06/a1-desk-laptop.jpg', 'label' => 'At the desk, working on a laptop', 'note' => '', 'pos' => '56 40'],
                ['r' => 'A2', 'f' => 'assets/photos/06/a2-desk-phone.jpg', 'label' => 'On the phone with a client', 'note' => '', 'pos' => '39 42'],
                ['r' => 'A3', 'f' => 'assets/photos/06/a3-desk-seated-wide.jpg', 'label' => 'Seated at the desk, wide', 'note' => '', 'pos' => '56 39'],
                ['r' => 'A4', 'f' => 'assets/photos/06/a4-desk-standing.jpg', 'label' => 'Standing by the desk', 'note' => '', 'pos' => '62 33'],
                ['r' => 'A5', 'f' => 'assets/photos/06/a5-home-office-desk.jpg', 'label' => 'Home office, laptop and dog', 'note' => '', 'pos' => '46 34'],
            ],
        ],
        '07' => [
            'title' => 'Editorial portraits',
            'photos' => [
                ['r' => 'A1', 'f' => 'assets/photos/07/a1-luxe-lounge-ai.jpg', 'label' => 'Luxe office lounge', 'note' => 'AI-generated', 'pos' => '75 18'],
                ['r' => 'A2', 'f' => 'assets/photos/07/a2-studio-full-length.jpg', 'label' => 'Studio editorial, full length', 'note' => '', 'pos' => '45 15'],
                ['r' => 'A3', 'f' => 'assets/photos/07/a3-studio-alt-pose.jpg', 'label' => 'Studio editorial, alternate pose', 'note' => '', 'pos' => '49 16'],
                ['r' => 'A4', 'f' => 'assets/photos/07/a4-black-blazer-gold.jpg', 'label' => 'Black blazer, gold blouse', 'note' => '', 'pos' => '56 23'],
                ['r' => 'A5', 'f' => 'assets/photos/07/a5-soft-editorial.jpg', 'label' => 'Soft editorial, close crop', 'note' => '', 'pos' => '48 45'],
                ['r' => 'A6', 'f' => 'assets/photos/07/a6-executive-office-ai.jpg', 'label' => 'Executive office portrait', 'note' => 'AI-generated', 'pos' => '48 24'],
                ['r' => 'A7', 'f' => 'assets/photos/07/a7-glass-office-ai.jpg', 'label' => 'Outside a glass office building', 'note' => 'AI-generated', 'pos' => '43 41'],
                ['r' => 'A8', 'f' => 'assets/photos/07/a8-lounge-seated-ai.jpg', 'label' => 'Lounge, seated portrait', 'note' => 'AI-generated', 'pos' => '49 44'],
                ['r' => 'A9', 'f' => 'assets/photos/07/a9-magazine-cover-ai.jpg', 'label' => 'Mock magazine cover', 'note' => 'AI-generated - not a real feature, text is garbled', 'pos' => '57 22'],
            ],
        ],
        '08' => [
            'title' => 'Sold & closing wins',
            'photos' => [
                ['r' => 'A1', 'f' => 'assets/photos/08/a1-just-sold-sellers.jpg', 'label' => 'JUST SOLD with the sellers', 'note' => 'small original', 'pos' => '38 58'],
                ['r' => 'A2', 'f' => 'assets/photos/08/a2-porch-sold-sign.jpg', 'label' => 'On the porch with a SOLD sign', 'note' => '', 'pos' => '50 39'],
                ['r' => 'A3', 'f' => 'assets/photos/08/a3-closing-day-sold.jpg', 'label' => 'Closing day, SOLD sign with client', 'note' => '', 'pos' => '57 34'],
                ['r' => 'A4', 'f' => 'assets/photos/08/a4-sold-yard-sign.jpg', 'label' => 'SOLD yard sign, Erika Page branding', 'note' => '', 'pos' => '39 69'],
                ['r' => 'A5', 'f' => 'assets/photos/08/a5-listing-announcement.jpg', 'label' => 'Living Luxury listing announcement', 'note' => '', 'pos' => '75 59'],
                ['r' => 'A6', 'f' => 'assets/photos/08/a6-lets-make-a-deal.jpg', 'label' => "Holding the LET'S MAKE A DEAL sign", 'note' => '', 'pos' => '55 42'],
            ],
        ],
        '09' => [
            'title' => 'Buyers & client moments',
            'photos' => [
                ['r' => 'A1', 'f' => 'assets/photos/09/a1-clients-sign-front-yard.jpg', 'label' => 'Clients with the sign, front yard', 'note' => '', 'pos' => '25 66'],
                ['r' => 'A2', 'f' => 'assets/photos/09/a2-family-celebrating.jpg', 'label' => 'Family celebrating in the yard', 'note' => '', 'pos' => '45 60'],
                ['r' => 'A3', 'f' => 'assets/photos/09/a3-buyers-inside-home.jpg', 'label' => 'Buyers inside the new home', 'note' => '', 'pos' => '56 54'],
                ['r' => 'A4', 'f' => 'assets/photos/09/a4-buyer-handoff.jpg', 'label' => 'Buyer handoff with the sign', 'note' => '', 'pos' => '75 60'],
                ['r' => 'A5', 'f' => 'assets/photos/09/a5-buyers-front-steps.jpg', 'label' => 'Buyers on the front steps', 'note' => '', 'pos' => '50 42'],
                ['r' => 'A6', 'f' => 'assets/photos/09/a6-buyers-group.jpg', 'label' => 'Buyers group with Erika', 'note' => '', 'pos' => '45 47'],
            ],
        ],
        '10' => [
            'title' => 'Media, on-air & video',
            'photos' => [
                ['r' => 'A1', 'f' => 'assets/photos/10/a1-green-screen-set.jpg', 'label' => 'Green-screen studio set', 'note' => '', 'pos' => '56 28'],
                ['r' => 'A2', 'f' => 'assets/photos/10/a2-filmed-interview.jpg', 'label' => 'Filmed interview, lights up', 'note' => '', 'pos' => '38 40'],
                ['r' => 'A3', 'f' => 'assets/photos/10/a3-behind-the-scenes.jpg', 'label' => 'Behind the scenes, wide', 'note' => '', 'pos' => '67 38'],
                ['r' => 'A4', 'f' => 'assets/photos/10/a4-interview-two-shot.jpg', 'label' => 'On-camera interview, two shot', 'note' => '', 'pos' => '32 39'],
                ['r' => 'A5', 'f' => 'assets/photos/10/a5-podcast-studio-ai.jpg', 'label' => 'Podcast studio look', 'note' => 'AI-generated', 'pos' => '53 42'],
            ],
        ],
        '11' => [
            'title' => 'Atlanta & locations',
            'photos' => [
                ['r' => 'A1', 'f' => 'assets/photos/11/a1-skyline-white-suit.jpg', 'label' => 'Skyline behind Erika, white suit', 'note' => 'small original', 'pos' => '67 33'],
                ['r' => 'A2', 'f' => 'assets/photos/11/a2-skyline-office-window.jpg', 'label' => 'Skyline through the office window', 'note' => '', 'pos' => '63 21'],
                ['r' => 'A3', 'f' => 'assets/photos/11/a3-childrens-healthcare.jpg', 'label' => 'Children\'s Healthcare of Atlanta', 'note' => '', 'pos' => '26 36'],
            ],
        ],
        '12' => [
            'title' => 'Escaluxe transportation',
            'photos' => [
                ['r' => 'A1', 'f' => 'assets/photos/12/a1-aviation-terminal.jpg', 'label' => 'Private aviation terminal', 'note' => '', 'pos' => '75 32'],
                ['r' => 'A2', 'f' => 'assets/photos/12/a2-beside-aircraft.jpg', 'label' => 'Beside a private aircraft', 'note' => '', 'pos' => '71 17'],
                ['r' => 'A3', 'f' => 'assets/photos/12/a3-helicopter-cabin.jpg', 'label' => 'Helicopter charter, in the cabin', 'note' => '', 'pos' => '50 43'],
                ['r' => 'A4', 'f' => 'assets/photos/12/a4-helicopter-tarmac.jpg', 'label' => 'On the tarmac with the pilot', 'note' => '', 'pos' => '44 44'],
                ['r' => 'A5', 'f' => 'assets/photos/12/a5-in-flight-headset.jpg', 'label' => 'In flight, headset on', 'note' => '', 'pos' => '58 39'],
                ['r' => 'A6', 'f' => 'assets/photos/12/a6-aircraft-cabin.jpg', 'label' => 'Private aircraft cabin', 'note' => '', 'pos' => '59 41'],
            ],
        ],
        '13' => [
            'title' => 'Lifestyle, travel & living',
            'photos' => [
                ['r' => 'A1', 'f' => 'assets/photos/13/a1-waterfall-travel.jpg', 'label' => 'Waterfall escape', 'note' => '', 'pos' => '65 67'],
                ['r' => 'A2', 'f' => 'assets/photos/13/a2-wine-cellar.jpg', 'label' => 'Wine cellar walk', 'note' => '', 'pos' => '47 36'],
                ['r' => 'A3', 'f' => 'assets/photos/13/a3-blush-gown-swing.jpg', 'label' => 'Blush gown on the swing', 'note' => '', 'pos' => '47 46'],
                ['r' => 'A4', 'f' => 'assets/photos/13/a4-vineyard-golden-hour.jpg', 'label' => 'Vineyard, golden hour', 'note' => '', 'pos' => '51 40'],
                ['r' => 'A5', 'f' => 'assets/photos/13/a5-garden-white-blazer.jpg', 'label' => 'Garden lounge, white blazer', 'note' => '', 'pos' => '39 35'],
                ['r' => 'A6', 'f' => 'assets/photos/13/a6-resort-sunset.jpg', 'label' => 'Resort sunset by the ocean', 'note' => '', 'pos' => '45 36'],
                ['r' => 'A7', 'f' => 'assets/photos/13/a7-rooftop-yellow.jpg', 'label' => 'Rooftop in yellow, umbrella and skyline trees', 'note' => '', 'pos' => '52 38'],
            ],
        ],
        '14' => [
            'title' => 'Community & networking',
            'photos' => [
                ['r' => 'A1', 'f' => 'assets/photos/14/a1-summit-with-mic.jpg', 'label' => 'Summit networking, with the mic', 'note' => '', 'pos' => '44 39'],
                ['r' => 'A2', 'f' => 'assets/photos/14/a2-branded-wall.jpg', 'label' => 'Branded wall backdrop', 'note' => '', 'pos' => '35 39'],
                ['r' => 'A3', 'f' => 'assets/photos/14/a3-team-and-partners.jpg', 'label' => 'Team and partners group photo', 'note' => '', 'pos' => '49 39'],
                ['r' => 'A4', 'f' => 'assets/photos/14/a4-industry-event-group.jpg', 'label' => 'Industry event, large group', 'note' => '', 'pos' => '51 41'],
                ['r' => 'A5', 'f' => 'assets/photos/14/a5-candid-colleague.jpg', 'label' => 'Candid with a colleague', 'note' => '', 'pos' => '55 48'],
            ],
        ],
        '15' => [
            'title' => 'Guide, product & collection covers',
            'photos' => [
                ['r' => 'A1', 'f' => 'assets/photos/15/c2-seller-strategy-guide.jpg', 'label' => 'Seller strategy guide cover', 'note' => 'designed artwork', 'pos' => ''],
                ['r' => 'A2', 'f' => 'assets/photos/15/c3-atlanta-relocation-playbook.jpg', 'label' => 'Atlanta relocation playbook cover', 'note' => 'designed artwork', 'pos' => ''],
                ['r' => 'A3', 'f' => 'assets/photos/15/c4-first-investment-property.jpg', 'label' => 'First investment property cover', 'note' => 'designed artwork', 'pos' => ''],
                ['r' => 'A4', 'f' => 'assets/photos/15/c1-gwinnett-selling-guide.jpg', 'label' => 'Gwinnett selling guide cover', 'note' => 'designed artwork', 'pos' => ''],
                ['r' => 'A5', 'f' => 'assets/photos/15/c5-seller-strategy-toolkit.jpg', 'label' => 'Seller Strategy Toolkit cover', 'note' => 'designed artwork', 'pos' => ''],
                ['r' => 'A6', 'f' => 'assets/photos/15/c6-atlanta-relocation-guide.jpg', 'label' => 'Atlanta Relocation Guide cover', 'note' => 'designed artwork', 'pos' => ''],
                ['r' => 'A7', 'f' => 'assets/photos/15/c7-agent-scripts-systems.jpg', 'label' => 'Agent Scripts & Systems cover', 'note' => 'designed artwork', 'pos' => ''],
                ['r' => 'A8', 'f' => 'assets/photos/15/c8-first-rental-blueprint.jpg', 'label' => 'First Rental Blueprint cover', 'note' => 'designed artwork', 'pos' => ''],
                ['r' => 'A9', 'f' => 'assets/photos/15/c9-reinvention-workbook.jpg', 'label' => 'Reinvention Workbook cover', 'note' => 'designed artwork', 'pos' => ''],
                ['r' => 'A10', 'f' => 'assets/photos/15/c10-workshop-materials.jpg', 'label' => 'Workshop Materials cover', 'note' => 'designed artwork', 'pos' => ''],
                ['r' => 'A11', 'f' => 'assets/photos/15/c11-body-care-collection.jpg', 'label' => 'Body Care collection card', 'note' => 'designed artwork', 'pos' => ''],
                ['r' => 'A12', 'f' => 'assets/photos/15/c12-home-fragrance-collection.jpg', 'label' => 'Home Fragrance collection card', 'note' => 'designed artwork', 'pos' => ''],
                ['r' => 'A13', 'f' => 'assets/photos/15/c13-living-essentials-collection.jpg', 'label' => 'Living Essentials collection card', 'note' => 'designed artwork', 'pos' => ''],
                ['r' => 'A14', 'f' => 'assets/photos/15/c14-guides-resources-shelf.jpg', 'label' => 'Guides & resources, three covers', 'note' => 'designed artwork', 'pos' => ''],
                ['r' => 'A15', 'f' => 'assets/photos/15/c15-digital-products-shelf.jpg', 'label' => 'Digital products, three covers', 'note' => 'designed artwork', 'pos' => ''],
                ['r' => 'A16', 'f' => 'assets/photos/15/c16-digital-products-banner.jpg', 'label' => 'Digital products wide banner', 'note' => 'designed artwork', 'pos' => ''],
            ],
        ],
    ],
    'slots' => [
        'home.atlanta-metro-established-au.img-erika-headshot-photo-o' => ['lib' => '01', 'pick' => 'A1'],
        'home.speaking-influence.img-erika-full-body-photo' => ['lib' => '02', 'pick' => 'A6'],
        'home.meet-erika.img-60-90-second-video-int' => ['lib' => '10', 'pick' => 'A1'],
        'home.erika-explains-latest-resour.img-video-thumbnail' => ['lib' => '10', 'pick' => 'A2'],
        'home.erika-explains-latest-resour.img-article-image' => ['lib' => '06', 'pick' => 'A5'],
        'home.moments-stages.img-keynote-atlanta-summit' => ['lib' => '03', 'pick' => 'A1'],
        'home.moments-stages.img-industry-panel' => ['lib' => '04', 'pick' => 'A1'],
        'home.moments-stages.img-adtv-on-set' => ['lib' => '10', 'pick' => 'A3'],
        'home.moments-stages.img-women-s-summit' => ['lib' => '14', 'pick' => 'A1'],
        'home.moments-stages.img-agent-mastermind' => ['lib' => '05', 'pick' => 'A2'],
        'home.moments-stages.img-community-event' => ['lib' => '14', 'pick' => 'A2'],
        'about.about-erika-page.img-erika-s-story-featured' => ['lib' => '03', 'pick' => 'A2'],
        'about.professional-bio.img-erika-editorial-portra' => ['lib' => '07', 'pick' => 'A2'],
        'about.entrepreneurship-ecosystem.img-escaluxe-ecosystem-tea' => ['lib' => '14', 'pick' => 'A3'],
        'about.speaking-media-authority.img-featured-video-erika-s' => ['lib' => '03', 'pick' => 'A7'],
        'sell.seller-stories.img-seller-video-story-1' => ['lib' => '08', 'pick' => 'A2'],
        'sell.seller-stories.img-seller-video-story-2' => ['lib' => '08', 'pick' => 'A4'],
        'sell.seller-stories.img-seller-video-story-3' => ['lib' => '08', 'pick' => 'A5'],
        'sell.seller-questions.img-sold-atlanta-listing-p' => ['lib' => '08', 'pick' => 'A1'],
        'homevalue.atlanta-home-value-strategy.img-erika-preparing-a-home' => ['lib' => '06', 'pick' => 'A1'],
        'buy.buy-with-erika.img-buyers-touring-an-atla' => ['lib' => '09', 'pick' => 'A3'],
        'buy.buying-strategy.img-buyers-at-new-home-key' => ['lib' => '09', 'pick' => 'A1'],
        'speaking.speaking.img-speaker-reel-preview' => ['lib' => '03', 'pick' => 'A1'],
        'speaking.speaker-bio.img-erika-keynote-stage-ph' => ['lib' => '03', 'pick' => 'A4'],
        'speaking.audience-types.img-speaker-reel-stage-cli' => ['lib' => '03', 'pick' => 'A9'],
        'collaborations.collaborations.img-brand-collaboration-sh' => ['lib' => '07', 'pick' => 'A3'],
        'lifestyle.lifestyle-magazine.img-atlanta-lifestyle-edit' => ['lib' => '13', 'pick' => 'A7'],
        'lifestyle.featured-stories.img-atlanta-skyline-featur' => ['lib' => '11', 'pick' => 'A2'],
        'lifestyle.featured-stories.img-travel-feature' => ['lib' => '13', 'pick' => 'A1'],
        'lifestyle.featured-stories.img-wealth-feature' => ['lib' => '12', 'pick' => 'A1'],
        'lifestyle.featured-stories.img-food-feature' => ['lib' => '13', 'pick' => 'A2'],
        'lifestyle.featured-stories.img-leadership-feature' => ['lib' => '05', 'pick' => 'A1'],
        'media.media-press.img-adtv-feature-clip' => ['lib' => '10', 'pick' => 'A4'],
        'media.on-screen-on-air.img-adtv-clip' => ['lib' => '10', 'pick' => 'A3'],
        'media.on-screen-on-air.img-podcast-episode' => ['lib' => '10', 'pick' => 'A2'],
        'media.on-screen-on-air.img-press-feature' => ['lib' => '03', 'pick' => 'A6'],
        'testimonials.google-zillow-video-testimon.img-client-story-highlight' => ['lib' => '08', 'pick' => 'A4'],
        'testimonials.video-testimonials.img-video-testimonial-1' => ['lib' => '09', 'pick' => 'A2'],
        'testimonials.video-testimonials.img-video-testimonial-2' => ['lib' => '09', 'pick' => 'A4'],
        'testimonials.video-testimonials.img-video-testimonial-3' => ['lib' => '09', 'pick' => 'A5'],
        'resources.featured-guides.img-erika-explains-ep-12' => ['lib' => '10', 'pick' => 'A2'],
        'resources.featured-guides.img-erika-explains-ep-11' => ['lib' => '10', 'pick' => 'A3'],
        'resources.featured-guides.img-erika-explains-ep-10' => ['lib' => '10', 'pick' => 'A4'],
        'explains.resources-erika-explains.img-erika-explains-series' => ['lib' => '10', 'pick' => 'A1'],
        'explains.latest-episode.img-ep-12-why-online-estim' => ['lib' => '10', 'pick' => 'A5'],
        'explains.latest-episode.img-ep-11' => ['lib' => '10', 'pick' => 'A3'],
        'explains.latest-episode.img-ep-10' => ['lib' => '10', 'pick' => 'A4'],
        'mentorship.mentorship.img-erika-coaching-agents' => ['lib' => '04', 'pick' => 'A3'],
        'mentorship.who-it-s-for.img-erika-coaching-masterm' => ['lib' => '05', 'pick' => 'A3'],
        'mentorship.agent-results.img-mentorship-video-progr' => ['lib' => '05', 'pick' => 'A4'],
        'transportation.escaluxe-transportation-logi.img-executive-fleet-photo' => ['lib' => '12', 'pick' => 'A1'],
        'living.the-story.img-escaluxe-living-lifest' => ['lib' => '13', 'pick' => 'A5'],
        'loc-atlanta.locations-atlanta-metro.img-atlanta-skyline-photo' => ['lib' => '11', 'pick' => 'A2'],
        'gallery.gallery.img-featured-gallery-highl' => ['lib' => '03', 'pick' => 'A1'],
        'gallery.section-2.img-erika-on-stage' => ['lib' => '03', 'pick' => 'A2'],
        'gallery.section-2.img-sold-family-home' => ['lib' => '08', 'pick' => 'A1'],
        'gallery.section-2.img-video-speaker-reel' => ['lib' => '03', 'pick' => 'A3'],
        'gallery.section-2.img-erika-editorial-portra' => ['lib' => '07', 'pick' => 'A2'],
        'gallery.section-2.img-video-client-story' => ['lib' => '09', 'pick' => 'A2'],
        'gallery.section-2.img-closing-day-keys-hando' => ['lib' => '08', 'pick' => 'A3'],
        'gallery.section-2.img-panel-discussion' => ['lib' => '04', 'pick' => 'A1'],
        'gallery.section-2.img-lifestyle-shoot-atlant' => ['lib' => '13', 'pick' => 'A2'],
        'gallery.section-2.img-video-erika-explains-b' => ['lib' => '10', 'pick' => 'A3'],
        'gallery.section-2.img-sold-gwinnett-colonial' => ['lib' => '08', 'pick' => 'A4'],
        // Slots that had no picture at all until now. Cover art comes from
        // library 15 (designed pieces); the rest reuse the closest photograph.
        'home.erika-explains-latest-resour.img-guide-cover' => ['lib' => '15', 'pick' => 'A4'],
        'home.sellers-first.img-atlanta-luxury-listing' => ['lib' => '08', 'pick' => 'A2'],
        'resources.featured-guides.img-seller-guide-cover' => ['lib' => '15', 'pick' => 'A1'],
        'resources.featured-guides.img-buyer-guide-cover' => ['lib' => '15', 'pick' => 'A2'],
        'resources.featured-guides.img-investing-guide-cover' => ['lib' => '15', 'pick' => 'A3'],
        'resources.resources.img-guides-resources-flat' => ['lib' => '15', 'pick' => 'A14'],
        'resources.digital-products.img-digital-products-previ' => ['lib' => '15', 'pick' => 'A16'],
        'products.resources-digital-products.img-digital-product-mockup' => ['lib' => '15', 'pick' => 'A15'],
        'products.section-2.img-product-cover' => ['lib' => '15', 'pick' => 'A5'],
        'products.section-2.img-product-cover-2' => ['lib' => '15', 'pick' => 'A6'],
        'products.section-2.img-product-cover-3' => ['lib' => '15', 'pick' => 'A7'],
        'products.section-2.img-product-cover-4' => ['lib' => '15', 'pick' => 'A8'],
        'products.section-2.img-product-cover-5' => ['lib' => '15', 'pick' => 'A9'],
        'products.section-2.img-product-cover-6' => ['lib' => '15', 'pick' => 'A10'],
        'living.the-collection.img-body-care-collection' => ['lib' => '15', 'pick' => 'A11'],
        'living.the-collection.img-home-fragrance-collect' => ['lib' => '15', 'pick' => 'A12'],
        'living.the-collection.img-living-essentials-coll' => ['lib' => '15', 'pick' => 'A13'],
        'lifestyle.featured-stories.img-luxury-interior-featur' => ['lib' => '07', 'pick' => 'A1'],
        'explains.latest-episode.img-ep-9' => ['lib' => '10', 'pick' => 'A5'],
        'explains.latest-episode.img-ep-8' => ['lib' => '03', 'pick' => 'A6'],
        'explains.latest-episode.img-ep-7' => ['lib' => '05', 'pick' => 'A1'],
        'explains.latest-episode.img-ep-6' => ['lib' => '06', 'pick' => 'A2'],
        'investing.investing-capital-acquisitio.img-atlanta-investment-pro' => ['lib' => '11', 'pick' => 'A2'],
        'living.escaluxe-living.img-escaluxe-living-produc' => ['lib' => '13', 'pick' => 'A6'],
        'pm.property-management.img-managed-property-exter' => ['lib' => '06', 'pick' => 'A5'],
        'contact.contact.img-erika-welcome-photo' => ['lib' => '01', 'pick' => 'A4'],
    ],
];
